name: frogio_santa_juana
description: Aplicación FROGIO para la Municipalidad de Santa Juana.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # Dependency Injection
  get_it: ^7.6.7
  
  # Utils
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  intl: ^0.18.1
  
  # UI
  google_fonts: ^6.1.0
  # lottie: ^3.0.0  # Comentado temporalmente
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  
  # Offline
  hive: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  
  # Image
  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  flutter_image_compress: ^2.1.0
  timeline_tile: ^2.0.0
  path: ^1.9.0

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    # - assets/animations/  # Comentado temporalmente

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700