name: frogio_santa_juana
description: Aplicación FROGIO para la Municipalidad de Santa Juana.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - versiones actualizadas y compatibles
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  
  # Dependencia requerida para web
  js: ^0.6.7
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # Dependency Injection
  get_it: ^7.6.7
  
  # Utils
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  intl: ^0.18.1
  
  # UI
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Maps - solo para móviles
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  
  # Image - versiones simplificadas
  image_picker: ^1.0.5
  flutter_image_compress: ^2.1.0
  timeline_tile: ^2.0.0
  path: ^1.8.3

  uuid: ^4.1.0
  geocoding: ^3.0.0
  photo_view: ^0.14.0
  video_player: ^2.7.2
  
  # Para compresión en web
  image: ^4.1.3
  
  shared_preferences: ^2.2.2
  
  # Offline
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700