name: frogio_santa_juana
description: Aplicación FROGIO para la Municipalidad de Santa Juana.
publish_to: 'none' # Evita la publicación en pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # Dependency Injection
  get_it: ^7.6.7
  
  # Utils
  dartz: ^0.10.1          # Either para manejo de errores
  equatable: ^2.0.5       # Comparación de objetos
  json_annotation: ^4.8.1 # Serialización
  intl: ^0.18.1           # Internacionalización
  
  # UI
  google_fonts: ^6.1.0
  lottie: ^3.0.0          # Animaciones
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0         # Efectos loading
  
  # Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  
  # Offline
  hive: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  
  # Image
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700