// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZd3_krKkXx-S33Sg3XZ78i5UQBOGQCTA',
    appId: '1:729189223627:web:187faa2b27d5439c2e9f4e',
    messagingSenderId: '729189223627',
    projectId: 'frogio-201f9',
    authDomain: 'frogio-201f9.firebaseapp.com',
    storageBucket: 'frogio-201f9.firebasestorage.app',
    measurementId: 'G-YV6JDQ3DP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_88yvH7X3ETGzyRCZ9jkjtmhw-wIIbnc',
    appId: '1:729189223627:android:86b56712a035c4ec2e9f4e',
    messagingSenderId: '729189223627',
    projectId: 'frogio-201f9',
    storageBucket: 'frogio-201f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxO035IWyTUc-XC_V51XYY_7JDZfXtSzw',
    appId: '1:729189223627:ios:494b5daeb457f9e62e9f4e',
    messagingSenderId: '729189223627',
    projectId: 'frogio-201f9',
    storageBucket: 'frogio-201f9.firebasestorage.app',
    iosBundleId: 'com.example.frogioSantaJuana',
  );
}